services:
  app:
    build:
      context: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      sh -c "yarn start --host 0.0.0.0 --disable-host-check"

volumes:
  node_modules:
